# Generated by Django 4.0.6 on 2022-07-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField(verbose_name='when was this created?')),
                ('materials', models.ManyToManyField(to='main_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='Decorated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='decorated date')),
                ('decoration', models.CharField(choices=[('S', 'Stickers'), ('M', 'Marker Designs'), ('C', 'Crayon Designs'), ('P', 'Pen Designs'), ('CC', 'Colored Pencil Designs'), ('RP', 'Regular Pencil Designs'), ('D', 'Drawings'), ('PD', 'Painted Designs/Art'), ('B', 'Beddazzled'), ('G', 'Glitter')], default='S', max_length=2)),
                ('origami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.origami')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
