# Generated by Django 4.0.6 on 2022-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origami',
            name='age',
            field=models.IntegerField(verbose_name='How long ago was this created (in years)?'),
        ),
    ]
